version: "3.7"

networks:
  ml_ops_dev_network:
    driver: bridge
    ipam:
      driver: bridge
      config:
      - subnet: 172.18.0.0/16

services:
  mysql:
    restart: always
    image: mysql:8.3.0
    container_name: mlflow_db
    ports:
      - "3306:3306"
    networks:
      ml_ops_dev_network:
        ipv4_address: 172.18.0.1

  # S3 server to save data
  minio:
    restart: always
    image: minio/minio:RELEASE.2024-01-31T20-20-33Z
    container_name: s3
    ports:
      - "9000:9000"
      - "9001:9001"
    networks:
      ml_ops_dev_network:
        ipv4_address: 172.18.0.2
    env_file:
      - .env
    command: server /data --console-address ':9001' --address ':9000'
    environment:
      - MINIO_ROOT_USER=${AWS_ACCESS_KEY_ID}
      - MINIO_ROOT_PASSWORD=${AWS_SECRET_ACCESS_KEY}
    volumes:
      - minio_data:/data

  # minio client 
  mc:
    image: minio/mc:RELEASE.2024-01-31T08-59-40Z
    container_name: s3_client